body:
- type: input
  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: |
        "You can add some description and screenshots here if you want."
    validations:
      required: false
  - type: textarea
    id: colors
    attributes:
      label: Colors
      placeholder: |
        "Please paste the colors (obtained via the _copy_ button) here, and surround the text with ``` to make sure it's displayed in a way that can be copied easily."
    validations:
      required: true
